#!/usr/bin/perl

# Copyright 2009-2012, Equinox Software, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# TODO
#
# * add getopt support
# * use tag generator to expand list of wanted fields?
# * insertion of constant-value fields
# * field mapping ("some text" -> 4)?

# csv-extractor FILENAME FIELD_LIST

use strict;
use warnings;

use Text::CSV;

my $csv = Text::CSV->new( {binary => 1});

open CSV, '<', shift or die "Can't open file $!\n";

while (<CSV>) {
    $csv->parse($_);
    die "Bad data on line $.\n$_\n" if ($csv->error_diag);
    my @chunks = $csv->fields;
    my @out = ();
    for my $chunk (@ARGV)
      { push @out, $chunks[$chunk] }
    print join("\t", @out), "\n";
}
