#!/usr/bin/perl

my $infile = $ARGV[0] || 'incoming.renumbered.mrc.xml';
my $outfile = $ARGV[1] || $infile . '.1per.xml';

open IN, '<', $infile;
open OUT,'>', $outfile;

$seenrec  = 0;
$stripcol = 0;

while (<IN>) {
  unless ($seenrec)
    { $seenrec = 1 if /^<record/ }
  print OUT unless $seenrec;
  if (m|^</collection|) {
    while (<IN>)
      { last if /^\n$/ }
  }
  s/\n// unless m|^</record|;
  print OUT;
}
