== Migration Deduplication Process

The deduplication process covers bibliographic records for items. Other kinds of records such as authorities and MFHDs for serials are not included in the deduplication process.  This process is updated periodically as we review the best ways to do this given that metadata in Evergreen changes as do cataloging practices.  

Two important terms to understand as part of the deduplication process are incumbent bibliographic records and incoming bibliographic records.  Incumbent records are defined as all the bib records in the library's database except those that are being brought in as part of the migration.  Incoming bib records are those that are being imported as part of the migration.  The migration deduplication uses conservative matching sets with some options that are customized for different users.  It is meant to reduce duplication of bibs that have common identifiers while preventing merges of materials that should not share a common bib record.  It is not an inclusive deduplication, which is to say that duplicate incumbent items are not matched against each other - only incoming materials are matched against incumbent ones.  It is also expected that some matches will not be made.  The algorithms are conservative and meant to prevent bad matches. 

The process begins by creating one list of incoming bib records and one of incumbent bib records.  Bibs may then be removed based on options set by the Evergreen instiution.  Then a list of potential matches are created using sections of defined criteria called match sets.  Different Evergreen institutions use different match sets.  This is an example of the 'tacs_isbn' match set, which is widely used:

* A criteria set that determines if the record likely is some form of Audio/Video Disc is set to false for both records.
* Normalized description fields must either match or both be empty
* The normalized author must match exactly.
* The normalized title.
* The normalized title part and title part name must match or both be empty.
* The publisher must not match a list of manga and comic book publishers (which use a seprate merge set).
* A normalized ISBN must be shared in common.
* The search formats must match.  So, for example, if a record has entries for book, large print book and dvd then it will only match to another record that has book, large print book and dvd.  If a single format is different between the two records it will not match.
* The publication date must match.

Once a list of potential matches are built, the scoring begins.  Scoring is done for each bib record setting a value between 0 and two billion. Most records have a score between 10 and 100 with some very detailed records getting much higher scores.  

This is an example of the most commonly used scoring system:

* 1 point for each identifier subfield from the 020, 022 and 024 MARC fields
* 2 points for each subject subfield from the 6xx MARC fields
* 1 point for each title subfield from the 210, 222 and 24x MARC fields as long as they are one of the following descriptive subfields: 'a','b','c','f','g','k','n','p','s', or '0'
* 1 point for each author subfield from the 100, 110, 111 and 130 MARC fields as long as they are one of the following descriptive subfields: 'a','b','c','d','e','f','g','j','k','l','n','p','q','t', or 'u'
* 1 point for each added entry from the 70x, 71x,72x, 73x, 74x, 75x, 80x, 81x, 83x

Once the scores are created, the highest scoring incumbent bib record is selected as the one for the incoming bib matching it to be merged to, unless the incumbent's score is lower than the incoming bib's, in which case the incoming bib is retained and no merge is created.

