\i 00-infrastructure.sql
\i 01-marc.sql
\i 02-barcodes.sql
\i 03-items.sql
\i 04-names.sql
\i 05-addresses.sql
\i 06-ils-specific.sql
\i 07-eg-specific.sql
\i 08-casting-and-validation.sql
\i 09-misc.sql
\i 10-staging.sql
\i 21-fixed-fields.sql
\i 22-anyarray.sql
--\i 99-deprecated.sql
