VACUUM ANALYZE VERBOSE acq.acq_lineitem_history ;
VACUUM ANALYZE VERBOSE acq.distribution_formula_entry ;
VACUUM ANALYZE VERBOSE acq.fund_allocation_percent ;
VACUUM ANALYZE VERBOSE acq.lineitem ;
VACUUM ANALYZE VERBOSE action.aged_circulation ;
VACUUM ANALYZE VERBOSE action.aged_hold_request ;
VACUUM ANALYZE VERBOSE action.circulation ;
VACUUM ANALYZE VERBOSE action.fieldset ;
VACUUM ANALYZE VERBOSE action.hold_request ;
VACUUM ANALYZE VERBOSE action.hold_transit_copy ;
VACUUM ANALYZE VERBOSE action.in_house_use ;
VACUUM ANALYZE VERBOSE action.non_cataloged_circulation ;
VACUUM ANALYZE VERBOSE action.non_cat_in_house_use ;
VACUUM ANALYZE VERBOSE action.transit_copy ;
VACUUM ANALYZE VERBOSE action_trigger.environment;
VACUUM ANALYZE VERBOSE action_trigger.event;
VACUUM ANALYZE VERBOSE action_trigger.event_definition;
VACUUM ANALYZE VERBOSE action_trigger.event_params;
VACUUM ANALYZE VERBOSE actor.address_alert ;
VACUUM ANALYZE VERBOSE actor.card ;
VACUUM ANALYZE VERBOSE actor.hours_of_operation ;
VACUUM ANALYZE VERBOSE actor.org_address ;
VACUUM ANALYZE VERBOSE actor.org_lasso_map ;
VACUUM ANALYZE VERBOSE actor.org_unit ;
VACUUM ANALYZE VERBOSE actor.org_unit_closed ;
VACUUM ANALYZE VERBOSE actor.org_unit_custom_tree_node ;
VACUUM ANALYZE VERBOSE actor.org_unit_proximity_adjustment ;
VACUUM ANALYZE VERBOSE actor.org_unit_setting ;
VACUUM ANALYZE VERBOSE actor.search_filter_group ;
VACUUM ANALYZE VERBOSE actor.stat_cat ;
VACUUM ANALYZE VERBOSE actor.stat_cat_entry ;
VACUUM ANALYZE VERBOSE actor.stat_cat_entry_default ;
VACUUM ANALYZE VERBOSE actor.stat_cat_entry_usr_map ;
VACUUM ANALYZE VERBOSE actor.toolbar ;
VACUUM ANALYZE VERBOSE actor.usr ;
VACUUM ANALYZE VERBOSE actor.usr_activity ;
VACUUM ANALYZE VERBOSE actor.usr_address ;
VACUUM ANALYZE VERBOSE actor.usr_message ;
VACUUM ANALYZE VERBOSE actor.usr_note ;
VACUUM ANALYZE VERBOSE actor.usr_org_unit_opt_in ;
VACUUM ANALYZE VERBOSE actor.usr_password_reset ;
VACUUM ANALYZE VERBOSE actor.usr_saved_search ;
VACUUM ANALYZE VERBOSE actor.usr_setting ;
VACUUM ANALYZE VERBOSE actor.usr_standing_penalty ;
VACUUM ANALYZE VERBOSE actor.workstation ;
VACUUM ANALYZE VERBOSE asset.call_number ;
VACUUM ANALYZE VERBOSE asset.copy ;
VACUUM ANALYZE VERBOSE asset.copy_location ;
VACUUM ANALYZE VERBOSE asset.copy_note ;
VACUUM ANALYZE VERBOSE asset.copy_part_map ;
VACUUM ANALYZE VERBOSE asset.copy_template ;
VACUUM ANALYZE VERBOSE asset.opac_visible_copies ;
VACUUM ANALYZE VERBOSE asset.stat_cat_entry_copy_map ;
VACUUM ANALYZE VERBOSE asset.uri_call_number_map ;
VACUUM ANALYZE VERBOSE auditor.actor_usr_address_history ;
VACUUM ANALYZE VERBOSE auditor.actor_usr_history ;
VACUUM ANALYZE VERBOSE auditor.asset_call_number_history ;
VACUUM ANALYZE VERBOSE auditor.asset_copy_history ;
VACUUM ANALYZE VERBOSE authority.bib_linking ;
VACUUM ANALYZE VERBOSE biblio.monograph_part ;
VACUUM ANALYZE VERBOSE biblio.peer_bib_copy_map ;
VACUUM ANALYZE VERBOSE biblio.record_entry ;
VACUUM ANALYZE VERBOSE booking.reservation ;
VACUUM ANALYZE VERBOSE booking.resource ;
VACUUM ANALYZE VERBOSE booking.resource_attr ;
VACUUM ANALYZE VERBOSE booking.resource_attr_value ;
VACUUM ANALYZE VERBOSE booking.resource_type ;
VACUUM ANALYZE VERBOSE config.barcode_completion ;
VACUUM ANALYZE VERBOSE config.circ_limit_set ;
VACUUM ANALYZE VERBOSE config.circ_matrix_matchpoint ;
VACUUM ANALYZE VERBOSE config.filter_dialog_filter_set ;
VACUUM ANALYZE VERBOSE config.floating_group_member ;
VACUUM ANALYZE VERBOSE config.hold_matrix_matchpoint ;
VACUUM ANALYZE VERBOSE config.idl_field_doc ;
VACUUM ANALYZE VERBOSE config.org_unit_setting_type_log ;
VACUUM ANALYZE VERBOSE config.remote_account ;
VACUUM ANALYZE VERBOSE config.weight_assoc ;
VACUUM ANALYZE VERBOSE config.z3950_source_credentials ;
VACUUM ANALYZE VERBOSE metabib.browse_entry_def_map ;
VACUUM ANALYZE VERBOSE metabib.record_attr_vector_list ;
VACUUM ANALYZE VERBOSE metabib.record_sorter ;
VACUUM ANALYZE VERBOSE money.billable_xact ;
VACUUM ANALYZE VERBOSE money.billing;
VACUUM ANALYZE VERBOSE money.bnm_desk_payment;
VACUUM ANALYZE VERBOSE money.cash_payment;
VACUUM ANALYZE VERBOSE money.check_payment;
VACUUM ANALYZE VERBOSE money.collections_tracker ;
VACUUM ANALYZE VERBOSE money.credit_card_payment;
VACUUM ANALYZE VERBOSE money.credit_payment;
VACUUM ANALYZE VERBOSE money.forgive_payment;
VACUUM ANALYZE VERBOSE money.goods_payment;
VACUUM ANALYZE VERBOSE money.grocery ;
VACUUM ANALYZE VERBOSE money.materialized_billable_xact_summary ;
VACUUM ANALYZE VERBOSE money.payment;
VACUUM ANALYZE VERBOSE money.work_payment;
VACUUM ANALYZE VERBOSE permission.grp_penalty_threshold ;
VACUUM ANALYZE VERBOSE permission.usr_work_ou_map ;
VACUUM ANALYZE VERBOSE reporter.output_folder ;
VACUUM ANALYZE VERBOSE reporter.report ;
VACUUM ANALYZE VERBOSE reporter.report_folder ;
VACUUM ANALYZE VERBOSE reporter.schedule ;
VACUUM ANALYZE VERBOSE reporter.template ;
VACUUM ANALYZE VERBOSE reporter.template_folder ;
VACUUM ANALYZE VERBOSE serial.distribution ;
VACUUM ANALYZE VERBOSE serial.record_entry ;
VACUUM ANALYZE VERBOSE serial.subscription ;
VACUUM ANALYZE VERBOSE vandelay.import_bib_trash_group ;
VACUUM ANALYZE VERBOSE vandelay.import_item ;
VACUUM ANALYZE VERBOSE vandelay.import_item_attr_definition ;
VACUUM ANALYZE VERBOSE vandelay.match_set ;
VACUUM ANALYZE VERBOSE vandelay.merge_profile ;
VACUUM ANALYZE VERBOSE vandelay.queue ;
VACUUM ANALYZE VERBOSE vandelay.queued_bib_record ;
